/**
 * Auto-generated TypeScript types from OpenAPI schema
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Generated on: 2025-11-01T18:15:17.276Z
 * 
 * To regenerate, run: npm run generate-types
 */

export interface Body_login_user_auth_token_post {
  grant_type?: any;
  username: string;
  password: string;
  scope?: string;
  client_id?: any;
  client_secret?: any;
}

export interface DispatchOptimizationRequest {
  truck_id: string;
  llm_model?: string;
  depot_location?: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface ReachableRangeRequest {
  origin_lat: number;
  origin_lon: number;
  budget_value: number;
  budget_type?: string;
}

export interface RouteRequest {
  from_location: string;
  to_location: string;
  llm_model?: string;
  use_ai_optimization?: boolean;
  departure_time?: any;
  arrival_time?: any;
  time_mode?: string;
  delivery_date?: any;
  vehicle_type?: string;
  notes?: any;
}

export interface Token {
  access_token: string;
  token_type?: string;
  expires_in: number;
}

export interface TomTomRouteRequest {
  origin_lat: number;
  origin_lon: number;
  dest_lat: number;
  dest_lon: number;
  travel_mode?: string;
  route_type?: string;
}

export interface TruckCreate {
  code: string;
  plate?: any;
  capacity_liters?: any;
  fuel_level_percent?: any;
  fuel_type?: string;
  status?: string;
}

export interface User {
  username: string;
  email: string;
  id: number;
  is_active?: boolean;
  created_at?: any;
}

export interface UserCreate {
  username: string;
  email: string;
  password: string;
}

export interface ValidationError {
  loc: any[];
  msg: string;
  type: string;
}

export interface WeatherRequest {
  city: string;
}

// API Endpoint Request/Response Types

export type optimize_route_ai_api_routes_optimize_postRequest = RouteRequest;

export type optimize_route_ai_api_routes_optimize_postResponse = any;

export type get_weather_info_api_weather_postRequest = WeatherRequest;

export type get_weather_info_api_weather_postResponse = any;

export type calculate_tomtom_route_api_routes_tomtom_postRequest = TomTomRouteRequest;

export type calculate_tomtom_route_api_routes_tomtom_postResponse = any;

export type calculate_range_api_routes_reachable_range_postRequest = ReachableRangeRequest;

export type calculate_range_api_routes_reachable_range_postResponse = any;

export type get_stations_api_stations_getResponse = any;

export type get_trucks_api_trucks_getResponse = any;

export type create_truck_api_trucks_postRequest = TruckCreate;

export type create_truck_api_trucks_postResponse = any;

export type get_truck_api_trucks__truck_id__getResponse = any;

export type get_station_api_stations__station_id__getResponse = any;

export type get_trips_api_trips_getResponse = any;

export type get_trip_api_trips__trip_id__getResponse = any;

export type health_check_api_health_getResponse = any;

export type register_user_auth_register_postRequest = UserCreate;

export type register_user_auth_register_postResponse = User;

export type login_user_auth_token_postResponse = Token;

export type get_current_user_info_auth_me_getResponse = User;

export type logout_user_auth_logout_postResponse = any;

export type optimize_dispatch_api_dispatch_optimize_postRequest = DispatchOptimizationRequest;

export type optimize_dispatch_api_dispatch_optimize_postResponse = any;

